# -*- coding: utf-8 -*-
"""clase 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iiMJLl1S577Poc5cBcopXIbTtrdUBpOE
"""

#Registros financieros semestral
#ingreso  monto mensual
#uso un bucle para que se repita el ingreso 6 veces
i=1
ingreso_mensual=0
ingreso_total=0
for i in range(6):
  ingreso_mensual=float(input("Ingrese el monto del mes "))
  #validar monto positivo
  while ingreso_mensual < 0:
    ingreso_mensual=float(input("Por favor, ingrese el monto mensual "))
  ingreso_total=ingreso_total + ingreso_mensual

print(f"El ingreso total del semestre es de {ingreso_total}.-")

#Registros financieros semestral


nombre=input("Hola, te solicitaré tus datos, empezamos \nIntroduce tu nombre ")
if len(nombre)==0: #valido el ingreso de caracteres
  print("ERROR. No ha ingresado su nombre.")
apellido=input("Ahora introduce tu apellido ")# ingreso y guardo  caracteres
if len(apellido)==0: #valido esta vex el ingreso de caracteres en apellido
  print("ERROR. No ha ingrsaso su apellido")
#Validacion y clasificsscion de la edad
edad=input("Cual es tu edad? ")
if int(edad )<=0: #compruebo una edad valida
    edad=input("ERROR. No ha ingresado una edad valida.")
elif int(edad) > 18:
    rango_etario= "Adulto"
elif int(edad)<15:
    rango_etario= "Niño/a"
elif int(edad)>15 and int(edad) <18:
    rango_etario= "Adolescente"
#Validacion de Email
email=input("Y finalmente, tu correo electronico ")
if len(email)==0 or email.find("@")=="":#valido que se haya ingresado caracteres en email
   print("ERROR.No ha ingresado un e-mail valido")
print("Gracias!", end='\n')
#ingreso  monto mensual
#uso un bucle para que se repita el ingreso 6 veces
i=1
ingreso_mensual=0
ingreso_total=0
for i in range(6):
  ingreso_mensual=float(input("Ingrese el monto del mes "))
  #validar monto positivo
  while ingreso_mensual < 0:
    ingreso_mensual=float(input("Por favor, ingrese el monto mensual "))
  ingreso_total=ingreso_total + ingreso_mensual
#muestro los datos ingresados
# utilzo .strip() de quitar espacios al final y al principio
# Utilizo .lower() para colocar en minusculas los caracteres ingresados
# utilizo .title()para colocar en mayusculas las iniciales
print(f"Datos Introducidos\n Nombre:\t{nombre.lower().strip().title()}\t Apellido:\t {apellido.lower().strip().title()})\n Edad:\t{edad.strip()}\n Rango Etario:\t{rango_etario}\n E-Mail:\t{email.lower().strip()}\n Ingreso Total Semestral:\t {ingreso_total}.-")