# -*- coding: utf-8 -*-
"""Clase 6 eje.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HEm0jjQNAs-42O5lgDqsPyF0W1fXytW2
"""

#ejercicio 1 clase 06
#Usando bucles, lista, capitalize() etc como indica la consigna
#creamos una lista llamada clientes
clientes=[]
clientes=["Laura", "Martin"," ","Susana"," " ]
"""
recorremos la lista clientes con un bucle verificando que
no este vacio el nombre, colocando la inicial en mayuscula
el resto de las letras en minusculas
y comrpbando que se hayan ingresado solo letras y no nuneros o caracteres es´peciales
"""
for i in range(len(clientes)):
 if clientes[i].capitalize().lower().strip().isalpha():
  #imprimo el cliente el numero nombre o mensaje no valido si corresponde
  print(f"Cliente {i+1}: {clientes[i]}")
 else:
  print(f"Cliente {i+1} no valido ")