# -*- coding: utf-8 -*-
"""Ej clase 5 mejorado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kWKVamqxURuX7JeU38lsGcU-vTLF5fSw
"""

#Mismo ejercio ingresando el tipo de moneda y validandolo
#Registros financieros semestral
#solicito su nobre apellido y valido con le) que haya caracteres ingrsados
nombre=input("Hola, te solicitaré tus datos, empezamos \nIntroduce tu nombre ")
if len(nombre)==0:
  print("ERROR. No ha ingresado su nombre.")
apellido=input("Ahora introduce tu apellido ")
if len(apellido)==0:
  print("ERROR. No ha ingrsaso su apellido")
#Validacion y clasificsscion de la edad
#con while True:
while True:
  #Try:
  edad=input("Cual es tu edad? ")
#valido que la edad sea un numero
  if edad.isdigit():
      edad=int(edad)
      if (edad )<=0: #compruebo una edad valida
        edad=input("ERROR. No ha ingresado una edad valida.")
      elif (edad) > 18:
        rango_etario= "Adulto"
      elif (edad)<15:
        rango_etario= "Niño/a"
      elif (edad)>15 and (edad) <18:
        rango_etario= "Adolescente"
      break
#except ValueError:
  else:
      print("ERROR. No ha ingresado una edad valida")

#Validacion de Email
email=input("Y finalmente, tu correo electronico ")
#valido que se haya ingresado caracteres en  y que sea un email valido
if len(email)==0 or email.find("@")=="" or email.find(".com"):
   print("ERROR.No ha ingresado un e-mail valido")

print("Gracias!", end='\n')
#Ahora comenzamos la tarea financiera}
#Eleccion de moneda
#validacion de la moneda
moneda=input("Ingresa el tipo de monenda $ (Peso) o U$S (Dólar)")
"""
if "$"   in moneda or "U$S" in moneda.upper():
  print("Gracias por tu eleccion")
else:
  print("ERROR. No ha ingresado una moneda valida")
"""
#utilizando While
while True:
  if "$"  in moneda or "U$S"  in moneda.upper():
    print("Muchas Gracias. Continuamos")
    break
  else:
    print("ERROR. No ha ingresado una moneda valida")
    moneda=input("Por favor, Ingrese la monenda $ (Peso) o U$S (Dólar)")

#ingreso  monto mensual
#uso un bucle para que se repita el ingreso 6 veces
i=1
ingreso_mensual=0
ingreso_total=0
for i in range(6):
  ingreso_mensual=float(input("Ingrese el monto del mes "))
  #validar monto positivo
  while ingreso_mensual < 0:
    ingreso_mensual=float(input("Por favor, ingrese el monto mensual "))
  ingreso_total=ingreso_total + ingreso_mensual
#muestro los datos ingresados
# utilzo .strip() de quitar espacios al final y al principio
# Utilizo .lower() para colocar en minusculas los caracteres ingresados
# utilizo .title()para colocar en mayusculas las iniciales
print(f"Datos Introducidos\n Nombre:\t{nombre.lower().strip().title()}\t Apellido:\t {apellido.lower().strip().title()})\n Edad:\t{edad}\n Rango Etario:\t{rango_etario}\n E-Mail:\t{email.lower().strip()}\n Ingreso Total Semestral:\t {moneda}{ingreso_total}.-")