# -*- coding: utf-8 -*-
"""Ej clase 5 sumando clase 6 y lectura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kWKVamqxURuX7JeU38lsGcU-vTLF5fSw
"""

#Mismo ejercio ingresando el tipo de moneda y validandolo
#Registros financieros semestral
#solicito ingreso de nombre apellido y valido con len() e isalpha() que haya letras y no caracteres especiales ni numeros ingresados
#en ambvos utilizoel bucle para que repita la operacion de solicitar datos hasta que no sean validos
nombre=input("Hola, te solicitaré tus datos, empezamos \nIntroduce tu nombre ")
while len(nombre)==0 or not nombre.isalpha():
  print("ERROR. No ha ingresado su nombre.")
  nombre=input("Por favor, introduce tu nombre ")
apellido=input("Ahora introduce tu apellido ")
while len(apellido)==0 or not apellido.isalpha():
  print("ERROR. No ha ingrsaso su apellido")
  apellido=input("Por favor, introduce tu apellido ")
#Validacion y clasificacion de la edad
#con while True:
while True:
  #solicito ingreso de edad
  edad=input("Cual es tu edad? ")
#valido que la edad sea un numero
  if edad.isdigit():
      edad=int(edad)
      if (edad )<=0: #compruebo una edad valida mayor a 0
        edad=input("ERROR. No ha ingresado una edad valida.")
      elif (edad) > 18: #categorizo
        rango_etario= "Adulto"
      elif (edad)<15:
        rango_etario= "Niño/a"
      elif (edad)>15 and (edad) <18:
        rango_etario= "Adolescente"
      break
#si no ha sido un numero el ingreso, señala eñl error y vuelve a solicitar ingreso de edad
  else:
      print("ERROR. No ha ingresado una edad valida")

#Validacion de Email
email=input("Ingrese su E-mail")
#valido que se haya ingresado caracteres en  y que sea un email valido
#if len(email)==0 or email.find("@")=="" or email.find(".com"):
#usando el bucle while hasta que ingrese un mail valido
while True:
  #email=input("Ingrese su E-mail")
  #if len(email)==0 or email.find("@")=="" or email.find(".com")=="":
 # if len(email)>0 and email.find("@")== 1 and email.find(".com")== 1:
  if len(email)>0 and "@" in email and ".com" in email:
    break
   #print("ERROR.No ha ingresado un e-mail valido")
  else: email=input("ERROR.Por favor, ingresa un e-mail valido")

print("Gracias!", end='\n')
#Ahora comenzamos la tarea financiera
#Eleccion de moneda
#validacion de la moneda
moneda=input("Ingresa el tipo de monenda $ (Peso) o U$S (Dólar)")
#utilizando While hasta que no se ingrese uno de los dos caracteres especiales
while True:
  if "$"  in moneda or "U$S"  in moneda.upper():
    print("Muchas Gracias. Continuamos")
    break
  else:
    print("ERROR. No ha ingresado una moneda valida")
    moneda=input("Por favor, Ingrese la monenda $ (Peso) o U$S (Dólar)")

#ingreso  monto mensual
#uso un bucle para que se repita el ingreso 6 veces
i=1
ingreso_mensual=0
ingreso_total=0
for i in range(6): #utilizo for porque se que seran 6 los ingresos
  while True:  #uso el bucle para que solicite el monto hasta que no sea valido : numeros y positivo
    try:
       ingreso_mensual=float(input(f"Por favor, ingrese el monto mensual {i+1} "))
       ingreso_mensual=float(ingreso_mensual)
       if ingreso_mensual>0:
          ingreso_total=ingreso_total+ ingreso_mensual #sumo los meses a medida que ingresan correctamente
          break
    except ValueError: #si no han ingresado un monto valido, señala el error y solicita que sea ingresado
      print("ERROR. No ha ingresado un monto valido")
print("Mucgas Gracias \n")
#muestro los datos ingresados
# utilzo .strip() de quitar espacios al final y al principio
# Utilizo .lower() para colocar en minusculas los caracteres ingresados
# utilizo .title()para colocar en mayusculas las iniciales
print(f"Datos Introducidos\n Nombre:\t{nombre.lower().strip().title()}\t Apellido:\t {apellido.lower().strip().title()})\n Edad:\t{edad}\n Rango Etario:\t{rango_etario}\n E-Mail:\t{email.lower().strip()}\n Ingreso Total Semestral:\t {moneda}{ingreso_total}.-")